name: flutter_demo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 图片缓存
  cached_network_image: ^1.1.1
  # Toast
  fluttertoast: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_plugin:
    path: flutter_plugin

flutter:
  uses-material-design: true
